### ISSUE TITLE
Request for new webhook: order.notes.updated

### ISSUE THREAD

**Issue by kythin** [airbrite/celery-api#14]
The integration I'm writing relies on the 'private notes' field to be updated by staff as the order progresses through production phases. I want to be able to update the customer accordingly depending on the content of the field.

So the quickest way to help us would be to simply add another webhook that fires when the 'private notes' field is updated, sending all the same order info etc as any other webhook. That would help a lot and save me from having to run a cron to check all orders for notes changes!

Thank you!

**Comment by bnguyen06** [comment]
@kythin You can now receive `order.notes.updated` webhooks when the private notes are updated.
